#!/bin/bash 

# Load basic functions to run this script.
source ./bin/functions.sh

# Check if the script is running as root.
if [[ $EUID -ne 0 ]]; then
   echo "This script must be ran as root."
   exit 1
fi

# Looping through parameters
while [[ "$#" -gt 0 ]]; do 
	install $1
	shift
done
install update