#!/bin/bash 

# Load basic functions to run this script.
source ./bin/functions.sh

# Check if the script is running as root.
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

# Looping through parameters
while [[ "$#" -gt 0 ]]; do 
	install $1
	shift
done
